name: polygon_crypto
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


#UI
  cupertino_icons: ^1.0.2

#NETWORK
  dio: ^5.2.1+1
  get_it: ^7.6.0
  equatable: ^2.0.5
  intl: ^0.18.1
  json_annotation: ^4.8.1
  bloc: ^8.1.2
  provider: ^6.0.5
  flutter_bloc: ^8.1.3

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.6.2


flutter:


  uses-material-design: true

assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
